import { useMemo } from "react";
import { Platform, StyleSheet } from "react-native";
import type { Palette } from "./theme";

export function useStyles(colors: Palette) {
  return useMemo(() => createStyles(colors), [colors]);
}

function createStyles(colors: Palette) {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: colors.bg },
    flex: { flex: 1, backgroundColor: "#000" },
    center: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: colors.bg },
    pad: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: Platform.OS === "android" ? 108 : 36, gap: 10 },
    topRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 12 },
    topCopy: { flex: 1, gap: 2 },
    topActions: { alignItems: "flex-end", gap: 8 },
    brand: { letterSpacing: 1.8, color: colors.kicker, fontSize: 12, fontWeight: "700" },
    kicker: { letterSpacing: 1.4, color: colors.kicker, fontSize: 12, fontWeight: "700", textTransform: "uppercase" },
    hello: { color: colors.muted, fontSize: 14 },
    title: { fontSize: 30, fontWeight: "700", color: colors.ink, letterSpacing: -0.4, marginTop: 4 },
    help: { color: colors.muted, fontSize: 15, lineHeight: 22 },
    label: {
      marginTop: 8,
      fontWeight: "700",
      fontSize: 12,
      letterSpacing: 1.1,
      textTransform: "uppercase",
      color: colors.faint,
    },
    section: {
      marginTop: 18,
      fontWeight: "700",
      fontSize: 12,
      letterSpacing: 1.2,
      textTransform: "uppercase",
      color: colors.faint,
    },
    input: {
      backgroundColor: colors.inputBg,
      borderColor: colors.line,
      borderWidth: 1,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 14,
      color: colors.ink,
      fontSize: 16,
    },
    passwordField: { position: "relative", justifyContent: "center" },
    passwordInput: { paddingRight: 52 },
    passwordToggle: {
      position: "absolute",
      right: 6,
      width: 40,
      height: 40,
      alignItems: "center",
      justifyContent: "center",
    },
    button: {
      backgroundColor: colors.primary,
      borderRadius: 14,
      minHeight: 52,
      paddingHorizontal: 16,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 8,
    },
    buttonText: { color: colors.primaryInk, fontWeight: "700", fontSize: 16 },
    secondary: {
      minHeight: 48,
      paddingHorizontal: 16,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.line,
      marginTop: 8,
    },
    secondaryText: { color: colors.ink, fontWeight: "700", fontSize: 15 },
    card: {
      backgroundColor: colors.elevated,
      borderColor: colors.line,
      borderWidth: 1,
      borderRadius: 16,
      padding: 16,
      marginTop: 8,
      gap: 6,
    },
    cardHead: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 },
    cardTitle: { fontWeight: "700", fontSize: 18, color: colors.ink },
    chip: { backgroundColor: colors.chipBg, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 4 },
    chipText: { color: colors.chipInk, fontSize: 12, fontWeight: "700" },
    muted: { color: colors.muted, fontSize: 14 },
    empty: { color: colors.muted, fontSize: 15, paddingVertical: 4 },
    link: { color: colors.kicker, fontWeight: "700", fontSize: 15 },
    row: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 12,
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.line,
    },
    rowTitle: { flex: 1, color: colors.ink, fontSize: 16 },
    doneText: { color: colors.muted },
    checkRow: { flexDirection: "row", alignItems: "center", gap: 12, paddingVertical: 10 },
    checkBox: {
      width: 22,
      height: 22,
      borderRadius: 6,
      borderWidth: 1.5,
      borderColor: colors.check,
      alignItems: "center",
      justifyContent: "center",
    },
    checkBoxOn: { backgroundColor: colors.checkOn, borderColor: colors.checkOn },
    checkMark: { color: colors.primaryInk, fontSize: 13, fontWeight: "700" },
    bannerDanger: { backgroundColor: colors.dangerBg, borderRadius: 12, padding: 12 },
    bannerDangerText: { color: colors.danger, fontSize: 14, fontWeight: "600" },
    dangerText: { color: colors.danger, fontWeight: "700" },
    sync: { borderRadius: 12, paddingHorizontal: 12, paddingVertical: 10, marginTop: 4 },
    syncText: { fontSize: 14, fontWeight: "600" },
    themeToggle: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.line,
      paddingHorizontal: 12,
      paddingVertical: 6,
      backgroundColor: colors.elevated,
    },
    themeToggleText: { color: colors.ink, fontSize: 13, fontWeight: "700" },
    pressed: { opacity: 0.72 },
    disabled: { opacity: 0.55 },
    cameraTop: {
      position: "absolute",
      top: 16,
      left: 16,
      right: 16,
    },
    cameraJob: { color: "#fff", fontSize: 15, fontWeight: "700" },
    cameraBar: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 28,
      paddingTop: 18,
      paddingBottom: Platform.OS === "android" ? 72 : 28,
      backgroundColor: "rgba(3,16,22,0.72)",
    },
    cameraSide: { minWidth: 64, minHeight: 48, alignItems: "center", justifyContent: "center" },
    cameraText: { color: "#fff", fontSize: 16, fontWeight: "700" },
    shutter: {
      width: 74,
      height: 74,
      borderRadius: 37,
      backgroundColor: "#fff",
      borderWidth: 4,
      borderColor: "rgba(255,255,255,0.35)",
    },
    photoRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    thumb: { width: 64, height: 64, borderRadius: 10, backgroundColor: colors.inputBg },
    thumbEmpty: {
      minHeight: 64,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.inputBg,
    },
    catGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
    catCard: {
      width: "48%",
      backgroundColor: colors.elevated,
      borderColor: colors.line,
      borderWidth: 1,
      borderRadius: 16,
      padding: 14,
      gap: 4,
    },
    catDot: { width: 8, height: 8, borderRadius: 4, marginBottom: 6 },
    catName: { color: colors.ink, fontSize: 16, fontWeight: "700" },
    catHint: { color: colors.muted, fontSize: 12 },
    catCount: { color: colors.ink, fontSize: 18, fontWeight: "700", marginTop: 8 },
    note: {
      minHeight: 88,
      backgroundColor: colors.inputBg,
      borderColor: colors.line,
      borderWidth: 1,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      color: colors.ink,
      fontSize: 16,
      textAlignVertical: "top",
    },
    addJob: {
      minHeight: 52,
      borderRadius: 14,
      borderWidth: 1,
      borderStyle: "dashed",
      borderColor: colors.line,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 8,
    },
    walkCard: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.line,
      backgroundColor: colors.elevated,
      padding: 16,
      gap: 4,
      marginTop: 8,
    },
    msgMine: { marginLeft: 28, backgroundColor: colors.primary, borderRadius: 14, padding: 12, gap: 4 },
    msgThem: { marginRight: 28, backgroundColor: colors.elevated, borderColor: colors.line, borderWidth: 1, borderRadius: 14, padding: 12, gap: 4 },
    msgWho: { fontSize: 12, fontWeight: "700" },
    actions: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    lineCard: {
      flexDirection: "row",
      gap: 10,
      alignItems: "center",
      backgroundColor: colors.elevated,
      borderColor: colors.line,
      borderWidth: 1,
      borderRadius: 14,
      padding: 10,
    },
    lineText: { flex: 1, color: colors.ink, fontSize: 15, lineHeight: 21 },
    previewBackdrop: { flex: 1, backgroundColor: "#000" },
    previewImage: { flex: 1, width: "100%" },
    previewClose: { paddingHorizontal: 20, paddingTop: 48, paddingBottom: 12 },
  });
}
