import { getEnv } from "@/lib/env";
import { captionFromInspection, inspectPhotoBuffer } from "@/server/ai/inspect-photo";

export type PhotoDescriptionInput = {
  mimeType: string;
  buffer?: Buffer;
  filename?: string;
  tags?: string[];
  hasGps?: boolean;
};

export type ProjectSummaryInput = {
  name: string;
  number?: string;
  status?: string;
  notes: string[];
  photoCount?: number;
  checklistDone?: number;
  checklistTotal?: number;
};

export interface AiService {
  readonly name: string;
  generateProjectSummary(input: ProjectSummaryInput): Promise<string>;
  generatePhotoDescription(input: PhotoDescriptionInput): Promise<string>;
  generateReport(input: { title: string; summary?: string }): Promise<string>;
  translateText(input: { text: string; targetLocale: string }): Promise<string>;
  generateChecklist(input: { jobType: string }): Promise<string[]>;
}

export class UnconfiguredAiService implements AiService {
  readonly name = "none";
  private fail(): never {
    throw new Error("AI is not connected yet. Set AI_DRIVER=internal for the on-device inspector, or connect a model provider later.");
  }
  generateProjectSummary() {
    return this.fail();
  }
  generatePhotoDescription() {
    return this.fail();
  }
  generateReport() {
    return this.fail();
  }
  translateText() {
    return this.fail();
  }
  generateChecklist() {
    return this.fail();
  }
}

export class LocalInspectorAiService implements AiService {
  readonly name = "internal";

  async generatePhotoDescription(input: PhotoDescriptionInput) {
    if (!input.buffer?.length) {
      return `Inspector: ${input.filename ?? "photo"} (${input.mimeType}). No pixels were available to inspect.`;
    }
    const inspection = await inspectPhotoBuffer(input.buffer);
    return captionFromInspection(inspection, {
      filename: input.filename,
      tags: input.tags,
      hasGps: input.hasGps,
    });
  }

  async generateProjectSummary(input: ProjectSummaryInput) {
    const photos = input.photoCount ?? 0;
    const done = input.checklistDone ?? 0;
    const total = input.checklistTotal ?? 0;
    const note = input.notes[0] ? ` Latest note: ${input.notes[0].slice(0, 180)}` : "";
    const label = [input.number, input.name].filter(Boolean).join(" ");
    return `Inspector summary for ${label}: status ${input.status ?? "unknown"}, ${photos} photo${photos === 1 ? "" : "s"}, checklists ${done}/${total}.${note}`;
  }

  async generateReport(input: { title: string; summary?: string }) {
    return `${input.title}\n\n${input.summary ?? "No inspector summary yet."}\n\nGenerated by the ZoneCam local inspector. A hosted model is not connected.`;
  }

  async translateText(input: { text: string; targetLocale: string }): Promise<string> {
    throw new Error(`Translation to ${input.targetLocale} needs a language model. It is not connected.`);
  }

  async generateChecklist(input: { jobType: string }) {
    const type = input.jobType.toLowerCase();
    if (type.includes("inspect")) {
      return ["Photograph existing conditions", "Note access issues", "Confirm measurements", "Review safety"];
    }
    if (type.includes("maint")) {
      return ["Photograph wear", "Check fasteners", "Test operation", "Document parts used"];
    }
    return ["Photograph before work", "Photograph progress", "Photograph completed work", "Customer walkthrough"];
  }
}

export function createAiService(): AiService {
  const driver = getEnv().AI_DRIVER;
  if (driver === "internal") return new LocalInspectorAiService();
  return new UnconfiguredAiService();
}

export function aiEnabled() {
  return getEnv().AI_DRIVER === "internal";
}
